from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from anastruct import SystemElements
import pickle
import functions
from mplwidget import MplWidget
import matplotlib.pyplot as plt
from pylatex import Document, Section, Figure, NoEscape


class Ui_TenshiCore(object):

    ss = SystemElements()
    figura = plt.figure()

    def setupUi(self, TenshiCore):
        TenshiCore.setObjectName("TenshiCore")
        TenshiCore.resize(2400, 1200)
        TenshiCore.setMinimumSize(QtCore.QSize(1200, 600))
        TenshiCore.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(TenshiCore)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.splitter_10 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_10)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_8)
        self.tabWidget.setMinimumSize(QtCore.QSize(1200, 600))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter_15 = QtWidgets.QSplitter(self.tab)
        self.splitter_15.setOrientation(QtCore.Qt.Vertical)
        self.splitter_15.setObjectName("splitter_15")
        self.splitter_12 = QtWidgets.QSplitter(self.splitter_15)
        self.splitter_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.label_33 = QtWidgets.QLabel(self.splitter_12)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setFrameShape(QtWidgets.QFrame.Box)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_33.setLineWidth(1)
        self.label_33.setMidLineWidth(0)
        self.label_33.setScaledContents(False)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_12)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(0)
        self.label.setMidLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.vigacy2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.vigacy2.setMinimumSize(QtCore.QSize(0, 25))
        self.vigacy2.setClearButtonEnabled(True)
        self.vigacy2.setObjectName("vigacy2")
        self.gridLayout.addWidget(self.vigacy2, 1, 3, 1, 1)
        self.vigacy1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.vigacy1.setMinimumSize(QtCore.QSize(0, 25))
        self.vigacy1.setClearButtonEnabled(True)
        self.vigacy1.setObjectName("vigacy1")
        self.gridLayout.addWidget(self.vigacy1, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setFrameShape(QtWidgets.QFrame.Box)
        self.label_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_42.setLineWidth(0)
        self.label_42.setMidLineWidth(2)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setLineWidth(0)
        self.label_2.setMidLineWidth(2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.vigacx2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.vigacx2.setMinimumSize(QtCore.QSize(0, 25))
        self.vigacx2.setClearButtonEnabled(True)
        self.vigacx2.setObjectName("vigacx2")
        self.gridLayout.addWidget(self.vigacx2, 1, 2, 1, 1)
        self.vigacx1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.vigacx1.setMinimumSize(QtCore.QSize(0, 25))
        self.vigacx1.setClearButtonEnabled(True)
        self.vigacx1.setObjectName("vigacx1")
        self.gridLayout.addWidget(self.vigacx1, 1, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setFrameShape(QtWidgets.QFrame.Box)
        self.label_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_43.setLineWidth(0)
        self.label_43.setMidLineWidth(2)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 0, 3, 1, 1)
        self.vigaadd = QtWidgets.QPushButton(self.splitter_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vigaadd.setFont(font)
        self.vigaadd.setObjectName("vigaadd")
        self.splitter_13 = QtWidgets.QSplitter(self.splitter_15)
        self.splitter_13.setMinimumSize(QtCore.QSize(0, 25))
        self.splitter_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_13.setOrientation(QtCore.Qt.Vertical)
        self.splitter_13.setObjectName("splitter_13")
        self.label_34 = QtWidgets.QLabel(self.splitter_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setFrameShape(QtWidgets.QFrame.Box)
        self.label_34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_34.setLineWidth(1)
        self.label_34.setScaledContents(False)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_13)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.trusscx2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.trusscx2.setMinimumSize(QtCore.QSize(0, 25))
        self.trusscx2.setClearButtonEnabled(True)
        self.trusscx2.setObjectName("trusscx2")
        self.gridLayout_5.addWidget(self.trusscx2, 1, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setFrameShape(QtWidgets.QFrame.Box)
        self.label_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_36.setLineWidth(0)
        self.label_36.setMidLineWidth(2)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 0, 4, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setFrameShape(QtWidgets.QFrame.Box)
        self.label_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_35.setLineWidth(0)
        self.label_35.setMidLineWidth(2)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 0, 0, 1, 1)
        self.trusscx1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.trusscx1.setMinimumSize(QtCore.QSize(0, 25))
        self.trusscx1.setClearButtonEnabled(True)
        self.trusscx1.setObjectName("trusscx1")
        self.gridLayout_5.addWidget(self.trusscx1, 1, 0, 1, 1)
        self.trussea = QtWidgets.QLineEdit(self.layoutWidget1)
        self.trussea.setMinimumSize(QtCore.QSize(0, 25))
        self.trussea.setClearButtonEnabled(True)
        self.trussea.setObjectName("trussea")
        self.gridLayout_5.addWidget(self.trussea, 1, 4, 1, 1)
        self.trusscy1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.trusscy1.setMinimumSize(QtCore.QSize(0, 25))
        self.trusscy1.setClearButtonEnabled(True)
        self.trusscy1.setObjectName("trusscy1")
        self.gridLayout_5.addWidget(self.trusscy1, 1, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setFrameShape(QtWidgets.QFrame.Box)
        self.label_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_41.setLineWidth(0)
        self.label_41.setMidLineWidth(2)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 0, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setFrameShape(QtWidgets.QFrame.Box)
        self.label_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_44.setLineWidth(0)
        self.label_44.setMidLineWidth(2)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 0, 2, 1, 1)
        self.trusscy2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.trusscy2.setMinimumSize(QtCore.QSize(0, 25))
        self.trusscy2.setClearButtonEnabled(True)
        self.trusscy2.setObjectName("trusscy2")
        self.gridLayout_5.addWidget(self.trusscy2, 1, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setFrameShape(QtWidgets.QFrame.Box)
        self.label_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_45.setLineWidth(0)
        self.label_45.setMidLineWidth(2)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 0, 3, 1, 1)
        self.trussadd = QtWidgets.QPushButton(self.splitter_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trussadd.setFont(font)
        self.trussadd.setObjectName("trussadd")
        self.splitter_14 = QtWidgets.QSplitter(self.splitter_15)
        self.splitter_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_14.setOrientation(QtCore.Qt.Vertical)
        self.splitter_14.setObjectName("splitter_14")
        self.label_37 = QtWidgets.QLabel(self.splitter_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setFrameShape(QtWidgets.QFrame.Box)
        self.label_37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_37.setLineWidth(1)
        self.label_37.setScaledContents(False)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_14)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.nodpv = QtWidgets.QLineEdit(self.layoutWidget2)
        self.nodpv.setMinimumSize(QtCore.QSize(0, 25))
        self.nodpv.setClearButtonEnabled(True)
        self.nodpv.setObjectName("nodpv")
        self.gridLayout_11.addWidget(self.nodpv, 1, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setFrameShape(QtWidgets.QFrame.Box)
        self.label_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_39.setLineWidth(0)
        self.label_39.setMidLineWidth(2)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_11.addWidget(self.label_39, 0, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setFrameShape(QtWidgets.QFrame.Box)
        self.label_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_38.setLineWidth(0)
        self.label_38.setMidLineWidth(2)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_11.addWidget(self.label_38, 0, 0, 1, 1)
        self.noduv = QtWidgets.QLineEdit(self.layoutWidget2)
        self.noduv.setMinimumSize(QtCore.QSize(0, 25))
        self.noduv.setClearButtonEnabled(True)
        self.noduv.setObjectName("noduv")
        self.gridLayout_11.addWidget(self.noduv, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setFrameShape(QtWidgets.QFrame.Box)
        self.label_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_40.setLineWidth(0)
        self.label_40.setMidLineWidth(2)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_11.addWidget(self.label_40, 0, 2, 1, 1)
        self.nodpos = QtWidgets.QLineEdit(self.layoutWidget2)
        self.nodpos.setMinimumSize(QtCore.QSize(0, 25))
        self.nodpos.setClearButtonEnabled(True)
        self.nodpos.setObjectName("nodpos")
        self.gridLayout_11.addWidget(self.nodpos, 1, 2, 1, 1)
        self.nodadd = QtWidgets.QPushButton(self.splitter_14)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nodadd.setFont(font)
        self.nodadd.setObjectName("nodadd")
        self.gridLayout_4.addWidget(self.splitter_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.splitter_6 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter = QtWidgets.QSplitter(self.splitter_6)
        self.splitter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setLineWidth(1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_9.setLineWidth(0)
        self.label_9.setMidLineWidth(3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.fixopos = QtWidgets.QLineEdit(self.layoutWidget3)
        self.fixopos.setMinimumSize(QtCore.QSize(0, 25))
        self.fixopos.setObjectName("fixopos")
        self.gridLayout_6.addWidget(self.fixopos, 2, 0, 1, 1)
        self.fixoadd = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fixoadd.setFont(font)
        self.fixoadd.setObjectName("fixoadd")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_7 = QtWidgets.QLabel(self.splitter_2)
        self.label_7.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setLineWidth(1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.layoutWidget4 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_12.setLineWidth(0)
        self.label_12.setMidLineWidth(3)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 0, 0, 1, 1)
        self.engpos = QtWidgets.QLineEdit(self.layoutWidget4)
        self.engpos.setMinimumSize(QtCore.QSize(0, 25))
        self.engpos.setObjectName("engpos")
        self.gridLayout_13.addWidget(self.engpos, 1, 0, 1, 1)
        self.engadd = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.engadd.setFont(font)
        self.engadd.setObjectName("engadd")
        self.gridLayout_14.addWidget(self.splitter_6, 0, 0, 1, 1)
        self.splitter_5 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_6 = QtWidgets.QLabel(self.splitter_3)
        self.label_6.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.layoutWidget5 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_16.setLineWidth(0)
        self.label_16.setMidLineWidth(3)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 2, 1, 1)
        self.movelpos = QtWidgets.QLineEdit(self.layoutWidget5)
        self.movelpos.setMinimumSize(QtCore.QSize(0, 25))
        self.movelpos.setObjectName("movelpos")
        self.gridLayout_2.addWidget(self.movelpos, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_11.setLineWidth(0)
        self.label_11.setMidLineWidth(3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_10.setLineWidth(0)
        self.label_10.setMidLineWidth(3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.movelang = QtWidgets.QLineEdit(self.layoutWidget5)
        self.movelang.setMinimumSize(QtCore.QSize(0, 25))
        self.movelang.setObjectName("movelang")
        self.gridLayout_2.addWidget(self.movelang, 1, 2, 1, 1)
        self.moveldir = QtWidgets.QLineEdit(self.layoutWidget5)
        self.moveldir.setMinimumSize(QtCore.QSize(0, 25))
        self.moveldir.setObjectName("moveldir")
        self.gridLayout_2.addWidget(self.moveldir, 1, 1, 1, 1)
        self.moveladd = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.moveladd.setFont(font)
        self.moveladd.setObjectName("moveladd")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_8 = QtWidgets.QLabel(self.splitter_4)
        self.label_8.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setLineWidth(1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.layoutWidget6 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_14.setLineWidth(0)
        self.label_14.setMidLineWidth(3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 1, 1, 1)
        self.molapos = QtWidgets.QLineEdit(self.layoutWidget6)
        self.molapos.setMinimumSize(QtCore.QSize(0, 25))
        self.molapos.setObjectName("molapos")
        self.gridLayout_3.addWidget(self.molapos, 1, 0, 1, 1)
        self.molatra = QtWidgets.QLineEdit(self.layoutWidget6)
        self.molatra.setMinimumSize(QtCore.QSize(0, 25))
        self.molatra.setObjectName("molatra")
        self.gridLayout_3.addWidget(self.molatra, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_13.setLineWidth(0)
        self.label_13.setMidLineWidth(3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_15.setLineWidth(0)
        self.label_15.setMidLineWidth(3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 2, 1, 1)
        self.molares = QtWidgets.QLineEdit(self.layoutWidget6)
        self.molares.setMinimumSize(QtCore.QSize(0, 25))
        self.molares.setObjectName("molares")
        self.gridLayout_3.addWidget(self.molares, 1, 2, 1, 1)
        self.molaadd = QtWidgets.QPushButton(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.molaadd.setFont(font)
        self.molaadd.setObjectName("molaadd")
        self.gridLayout_14.addWidget(self.splitter_5, 0, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setFrameShape(QtWidgets.QFrame.Box)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_26.setLineWidth(1)
        self.label_26.setMidLineWidth(0)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_16.addWidget(self.label_26, 0, 0, 1, 1)
        self.distadd = QtWidgets.QPushButton(self.tab_3)
        self.distadd.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.distadd.setFont(font)
        self.distadd.setObjectName("distadd")
        self.gridLayout_16.addWidget(self.distadd, 2, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.loadq = QtWidgets.QLineEdit(self.tab_3)
        self.loadq.setMinimumSize(QtCore.QSize(0, 25))
        self.loadq.setClearButtonEnabled(True)
        self.loadq.setObjectName("loadq")
        self.gridLayout_9.addWidget(self.loadq, 1, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setFrameShape(QtWidgets.QFrame.Box)
        self.label_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_27.setLineWidth(0)
        self.label_27.setMidLineWidth(2)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 0, 0, 1, 1)
        self.distpos = QtWidgets.QLineEdit(self.tab_3)
        self.distpos.setMinimumSize(QtCore.QSize(0, 25))
        self.distpos.setClearButtonEnabled(True)
        self.distpos.setObjectName("distpos")
        self.gridLayout_9.addWidget(self.distpos, 1, 0, 1, 1)
        self.loadqi = QtWidgets.QLineEdit(self.tab_3)
        self.loadqi.setMinimumSize(QtCore.QSize(0, 25))
        self.loadqi.setClearButtonEnabled(True)
        self.loadqi.setObjectName("loadqi")
        self.gridLayout_9.addWidget(self.loadqi, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setFrameShape(QtWidgets.QFrame.Box)
        self.label_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_29.setLineWidth(0)
        self.label_29.setMidLineWidth(2)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_9.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setFrameShape(QtWidgets.QFrame.Box)
        self.label_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_28.setLineWidth(0)
        self.label_28.setMidLineWidth(2)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 0, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.splitter_9 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.label_25 = QtWidgets.QLabel(self.splitter_9)
        self.label_25.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setFrameShape(QtWidgets.QFrame.Box)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_25.setLineWidth(1)
        self.label_25.setMidLineWidth(0)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.layoutWidget7 = QtWidgets.QWidget(self.splitter_9)
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_18.setLineWidth(0)
        self.label_18.setMidLineWidth(2)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 0, 0, 1, 1)
        self.pontyint = QtWidgets.QLineEdit(self.layoutWidget7)
        self.pontyint.setMinimumSize(QtCore.QSize(0, 25))
        self.pontyint.setClearButtonEnabled(True)
        self.pontyint.setObjectName("pontyint")
        self.gridLayout_7.addWidget(self.pontyint, 1, 1, 1, 1)
        self.pontadd = QtWidgets.QPushButton(self.layoutWidget7)
        self.pontadd.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pontadd.setFont(font)
        self.pontadd.setObjectName("pontadd")
        self.gridLayout_7.addWidget(self.pontadd, 2, 0, 1, 4)
        self.pontxint = QtWidgets.QLineEdit(self.layoutWidget7)
        self.pontxint.setMinimumSize(QtCore.QSize(0, 25))
        self.pontxint.setClearButtonEnabled(True)
        self.pontxint.setObjectName("pontxint")
        self.gridLayout_7.addWidget(self.pontxint, 1, 2, 1, 1)
        self.pontpos = QtWidgets.QLineEdit(self.layoutWidget7)
        self.pontpos.setMinimumSize(QtCore.QSize(0, 25))
        self.pontpos.setClearButtonEnabled(True)
        self.pontpos.setObjectName("pontpos")
        self.gridLayout_7.addWidget(self.pontpos, 1, 0, 1, 1)
        self.pontrot = QtWidgets.QLineEdit(self.layoutWidget7)
        self.pontrot.setMinimumSize(QtCore.QSize(0, 25))
        self.pontrot.setClearButtonEnabled(True)
        self.pontrot.setObjectName("pontrot")
        self.gridLayout_7.addWidget(self.pontrot, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_20.setLineWidth(0)
        self.label_20.setMidLineWidth(2)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_21.setLineWidth(0)
        self.label_21.setMidLineWidth(2)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_19.setLineWidth(0)
        self.label_19.setMidLineWidth(2)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 0, 1, 1, 1)
        self.gridLayout_17.addWidget(self.splitter_9, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_22.setLineWidth(1)
        self.label_22.setMidLineWidth(0)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setFrameShape(QtWidgets.QFrame.Box)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_24.setLineWidth(0)
        self.label_24.setMidLineWidth(2)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 0, 1, 1, 1)
        self.momint = QtWidgets.QLineEdit(self.tab_3)
        self.momint.setMinimumSize(QtCore.QSize(0, 25))
        self.momint.setClearButtonEnabled(True)
        self.momint.setObjectName("momint")
        self.gridLayout_8.addWidget(self.momint, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setFrameShape(QtWidgets.QFrame.Box)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_23.setLineWidth(0)
        self.label_23.setMidLineWidth(2)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 0, 0, 1, 1)
        self.mompos = QtWidgets.QLineEdit(self.tab_3)
        self.mompos.setMinimumSize(QtCore.QSize(0, 25))
        self.mompos.setClearButtonEnabled(True)
        self.mompos.setObjectName("mompos")
        self.gridLayout_8.addWidget(self.mompos, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.momadd = QtWidgets.QPushButton(self.tab_3)
        self.momadd.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.momadd.setFont(font)
        self.momadd.setObjectName("momadd")
        self.gridLayout_10.addWidget(self.momadd, 2, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.salvart = QtWidgets.QLineEdit(self.tab_4)
        self.salvart.setMinimumSize(QtCore.QSize(0, 25))
        self.salvart.setClearButtonEnabled(True)
        self.salvart.setObjectName("salvart")
        self.verticalLayout.addWidget(self.salvart)
        self.salvaradd = QtWidgets.QPushButton(self.tab_4)
        self.salvaradd.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.salvaradd.setFont(font)
        self.salvaradd.setObjectName("salvaradd")
        self.verticalLayout.addWidget(self.salvaradd)
        self.gridLayout_18.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.carregart = QtWidgets.QLineEdit(self.tab_4)
        self.carregart.setMinimumSize(QtCore.QSize(0, 25))
        self.carregart.setClearButtonEnabled(True)
        self.carregart.setObjectName("carregart")
        self.verticalLayout_2.addWidget(self.carregart)
        self.carregaradd = QtWidgets.QPushButton(self.tab_4)
        self.carregaradd.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.carregaradd.setFont(font)
        self.carregaradd.setObjectName("carregaradd")
        self.verticalLayout_2.addWidget(self.carregaradd)
        self.gridLayout_18.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_10)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.MplWidget = MplWidget(self.splitter_7)
        self.MplWidget.setMinimumSize(QtCore.QSize(1000, 980))
        self.MplWidget.setObjectName("MplWidget")
        self.widget = QtWidgets.QWidget(self.splitter_7)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radiostr = QtWidgets.QRadioButton(self.widget)
        self.radiostr.setObjectName("radiostr")
        self.horizontalLayout.addWidget(self.radiostr)
        self.radioapo = QtWidgets.QRadioButton(self.widget)
        self.radioapo.setObjectName("radioapo")
        self.horizontalLayout.addWidget(self.radioapo)
        self.radionorm = QtWidgets.QRadioButton(self.widget)
        self.radionorm.setObjectName("radionorm")
        self.horizontalLayout.addWidget(self.radionorm)
        self.radiocort = QtWidgets.QRadioButton(self.widget)
        self.radiocort.setObjectName("radiocort")
        self.horizontalLayout.addWidget(self.radiocort)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radiomom = QtWidgets.QRadioButton(self.widget)
        self.radiomom.setObjectName("radiomom")
        self.horizontalLayout_2.addWidget(self.radiomom)
        self.radiodes = QtWidgets.QRadioButton(self.widget)
        self.radiodes.setObjectName("radiodes")
        self.horizontalLayout_2.addWidget(self.radiodes)
        self.radioaio = QtWidgets.QRadioButton(self.widget)
        self.radioaio.setObjectName("radioaio")
        self.horizontalLayout_2.addWidget(self.radioaio)
        self.checkexp = QtWidgets.QCheckBox(self.widget)
        self.checkexp.setObjectName("checkexp")
        self.horizontalLayout_2.addWidget(self.checkexp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_12.addWidget(self.splitter_10, 0, 0, 1, 1)
        TenshiCore.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TenshiCore)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 25))
        self.menubar.setObjectName("menubar")
        self.menuOp_es = QtWidgets.QMenu(self.menubar)
        self.menuOp_es.setObjectName("menuOp_es")
        self.menuResetar_valores = QtWidgets.QMenu(self.menuOp_es)
        self.menuResetar_valores.setObjectName("menuResetar_valores")
        TenshiCore.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TenshiCore)
        self.statusbar.setObjectName("statusbar")
        TenshiCore.setStatusBar(self.statusbar)
        self.ajuda = QtWidgets.QAction(TenshiCore)
        self.ajuda.setObjectName("ajuda")
        self.salvar = QtWidgets.QAction(TenshiCore)
        self.salvar.setObjectName("salvar")
        self.carregar = QtWidgets.QAction(TenshiCore)
        self.carregar.setObjectName("carregar")
        self.resetforces = QtWidgets.QAction(TenshiCore)
        self.resetforces.setObjectName("resetforces")
        self.resetudo = QtWidgets.QAction(TenshiCore)
        self.resetudo.setObjectName("resetudo")
        self.checkreactions = QtWidgets.QAction(TenshiCore)
        self.checkreactions.setCheckable(True)
        self.checkreactions.setObjectName("checkreactions")
        self.checkaxials = QtWidgets.QAction(TenshiCore)
        self.checkaxials.setCheckable(True)
        self.checkaxials.setObjectName("checkaxials")
        self.checkmoments = QtWidgets.QAction(TenshiCore)
        self.checkmoments.setCheckable(True)
        self.checkmoments.setObjectName("checkmoments")
        self.checkshears = QtWidgets.QAction(TenshiCore)
        self.checkshears.setCheckable(True)
        self.checkshears.setObjectName("checkshears")
        self.checkdisplacements = QtWidgets.QAction(TenshiCore)
        self.checkdisplacements.setCheckable(True)
        self.checkdisplacements.setObjectName("checkdisplacements")
        self.checkaio = QtWidgets.QAction(TenshiCore)
        self.checkaio.setCheckable(True)
        self.checkaio.setChecked(True)
        self.checkaio.setObjectName("checkaio")
        self.checkstructure = QtWidgets.QAction(TenshiCore)
        self.checkstructure.setCheckable(True)
        self.checkstructure.setChecked(False)
        self.checkstructure.setObjectName("checkstructure")
        self.menuResetar_valores.addAction(self.resetforces)
        self.menuResetar_valores.addAction(self.resetudo)
        self.menuOp_es.addAction(self.menuResetar_valores.menuAction())
        self.menuOp_es.addAction(self.ajuda)
        self.menubar.addAction(self.menuOp_es.menuAction())

        self.retranslateUi(TenshiCore)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TenshiCore)
        TenshiCore.setTabOrder(self.molaadd, self.molapos)
        TenshiCore.setTabOrder(self.molapos, self.molatra)
        TenshiCore.setTabOrder(self.molatra, self.molares)
        TenshiCore.setTabOrder(self.molares, self.moveladd)
        TenshiCore.setTabOrder(self.moveladd, self.movelpos)
        TenshiCore.setTabOrder(self.movelpos, self.moveldir)
        TenshiCore.setTabOrder(self.moveldir, self.movelang)
        TenshiCore.setTabOrder(self.movelang, self.engadd)
        TenshiCore.setTabOrder(self.engadd, self.engpos)
        TenshiCore.setTabOrder(self.engpos, self.fixoadd)
        TenshiCore.setTabOrder(self.fixoadd, self.fixopos)
        TenshiCore.setTabOrder(self.fixopos, self.mompos)
        TenshiCore.setTabOrder(self.mompos, self.momint)
        TenshiCore.setTabOrder(self.momint, self.distpos)
        TenshiCore.setTabOrder(self.distpos, self.loadqi)
        TenshiCore.setTabOrder(self.loadqi, self.loadq)
        TenshiCore.setTabOrder(self.loadq, self.pontpos)
        TenshiCore.setTabOrder(self.pontpos, self.pontyint)
        TenshiCore.setTabOrder(self.pontyint, self.pontxint)
        TenshiCore.setTabOrder(self.pontxint, self.pontrot)
        TenshiCore.setTabOrder(self.pontrot, self.vigaadd)
        TenshiCore.setTabOrder(self.vigaadd, self.vigacx1)
        TenshiCore.setTabOrder(self.vigacx1, self.vigacy1)
        TenshiCore.setTabOrder(self.vigacy1, self.trusscx1)
        TenshiCore.setTabOrder(self.trusscx1, self.trussea)
        TenshiCore.setTabOrder(self.trussea, self.trussadd)
        TenshiCore.setTabOrder(self.trussadd, self.nodpv)
        TenshiCore.setTabOrder(self.nodpv, self.noduv)
        TenshiCore.setTabOrder(self.noduv, self.nodpos)
        TenshiCore.setTabOrder(self.nodpos, self.nodadd)
        TenshiCore.setTabOrder(self.nodadd, self.trusscy1)
        TenshiCore.setTabOrder(self.trusscy1, self.pontadd)
        TenshiCore.setTabOrder(self.pontadd, self.distadd)
        TenshiCore.setTabOrder(self.distadd, self.momadd)

        self.vigaadd.clicked.connect(self.vigas)
        self.fixoadd.clicked.connect(self.supfixo)
        self.moveladd.clicked.connect(self.supmovel)
        self.pontadd.clicked.connect(self.pointload)
        self.momadd.clicked.connect(self.moment)
        self.distadd.clicked.connect(self.load)
        self.resetforces.triggered.connect(self.reset)
        self.resetudo.triggered.connect(self.resetall)
        self.molaadd.clicked.connect(self.supspring)
        self.trussadd.clicked.connect(self.truss)
        self.nodadd.clicked.connect(self.node)
        self.engadd.clicked.connect(self.supeng)
        self.salvaradd.clicked.connect(self.save)
        self.carregaradd.clicked.connect(self.sload)
        self.sethidden()
        self.radiostr.clicked.connect(self.visualize)
        self.radioaio.clicked.connect(self.visualize)
        self.radiomom.clicked.connect(self.visualize)
        self.radiocort.clicked.connect(self.visualize)
        self.radioapo.clicked.connect(self.visualize)
        self.radionorm.clicked.connect(self.visualize)
        self.radiodes.clicked.connect(self.visualize)
        self.checkexp.stateChanged.connect(self.showexp)

    def retranslateUi(self, TenshiCore):
        _translate = QtCore.QCoreApplication.translate
        TenshiCore.setWindowTitle(_translate("TenshiCore", "Tenshi"))
        self.label_33.setText(_translate("TenshiCore", "Viga"))
        self.label.setText(_translate("TenshiCore", "Coordenada X1"))
        self.label_42.setText(_translate("TenshiCore", "Coordenada X2"))
        self.label_2.setText(_translate("TenshiCore", "Coordenada Y1"))
        self.label_43.setText(_translate("TenshiCore", "Coordenada Y2"))
        self.vigaadd.setText(_translate("TenshiCore", "Adicionar"))
        self.label_34.setText(_translate("TenshiCore", "Treliça"))
        self.label_36.setText(_translate("TenshiCore", "EA"))
        self.label_35.setText(_translate("TenshiCore", "Coordenada X1"))
        self.label_41.setText(_translate("TenshiCore", "Coordenada Y1"))
        self.label_44.setText(_translate("TenshiCore", "Coordenada X2"))
        self.label_45.setText(_translate("TenshiCore", "Coordenada Y2"))
        self.trussadd.setText(_translate("TenshiCore", "Adicionar"))
        self.label_37.setText(_translate("TenshiCore", "Nó"))
        self.label_39.setText(_translate("TenshiCore", "Coordenada X"))
        self.label_38.setText(_translate("TenshiCore", "Adicionar Após o Nó:"))
        self.label_40.setText(_translate("TenshiCore", "Coordenada Y"))
        self.nodadd.setText(_translate("TenshiCore", "Adicionar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TenshiCore", "Elementos"))
        self.label_5.setText(_translate("TenshiCore", "Apoio Fixo"))
        self.label_9.setText(_translate("TenshiCore", "Posição"))
        self.fixoadd.setText(_translate("TenshiCore", "Adicionar"))
        self.label_7.setText(_translate("TenshiCore", "Engaste"))
        self.label_12.setText(_translate("TenshiCore", "Posição"))
        self.engadd.setText(_translate("TenshiCore", "Adicionar"))
        self.label_6.setText(_translate("TenshiCore", "Apoio Móvel"))
        self.label_16.setText(_translate("TenshiCore", "Ângulo"))
        self.label_11.setText(_translate("TenshiCore", "Direção"))
        self.label_10.setText(_translate("TenshiCore", "Posição"))
        self.moveladd.setText(_translate("TenshiCore", "Adicionar"))
        self.label_8.setText(_translate("TenshiCore", "Apoio de Mola"))
        self.label_14.setText(_translate("TenshiCore", "Eixo de Translação"))
        self.label_13.setText(_translate("TenshiCore", "Posição"))
        self.label_15.setText(_translate("TenshiCore", "Resistência"))
        self.molaadd.setText(_translate("TenshiCore", "Adicionar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TenshiCore", "Apoios"))
        self.label_26.setText(_translate("TenshiCore", "Carga Distribuída"))
        self.distadd.setText(_translate("TenshiCore", "Adicionar"))
        self.label_27.setText(_translate("TenshiCore", "Posição"))
        self.label_29.setText(_translate("TenshiCore", "Intensidade Final"))
        self.label_28.setText(_translate("TenshiCore", "Intensidade Inicial"))
        self.label_25.setText(_translate("TenshiCore", "Carga Pontual"))
        self.label_18.setText(_translate("TenshiCore", "Posição"))
        self.pontadd.setText(_translate("TenshiCore", "Adicionar"))
        self.label_20.setText(_translate("TenshiCore", "Intensidade em X"))
        self.label_21.setText(_translate("TenshiCore", "Rotação"))
        self.label_19.setText(_translate("TenshiCore", "Intensidade em Y"))
        self.label_22.setText(_translate("TenshiCore", "Momento"))
        self.label_24.setText(_translate("TenshiCore", "Intensidade"))
        self.label_23.setText(_translate("TenshiCore", "Posição"))
        self.momadd.setText(_translate("TenshiCore", "Adicionar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("TenshiCore", "Esforços"))
        self.label_3.setText(_translate("TenshiCore", "Nome da Estrutura a Salvar"))
        self.salvaradd.setText(_translate("TenshiCore", "Salvar"))
        self.label_4.setText(_translate("TenshiCore", "Nome da Estrutura a Carregar"))
        self.carregaradd.setText(_translate("TenshiCore", "Carregar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("TenshiCore", "Salvar e Carregar"))
        self.radiostr.setText(_translate("TenshiCore", "Estrutura"))
        self.radioapo.setText(_translate("TenshiCore", "Apoios"))
        self.radionorm.setText(_translate("TenshiCore", "Normais"))
        self.radiocort.setText(_translate("TenshiCore", "Cortante"))
        self.radiomom.setText(_translate("TenshiCore", "Momento "))
        self.radiodes.setText(_translate("TenshiCore", "Deslocamento"))
        self.radioaio.setText(_translate("TenshiCore", "AIO"))
        self.checkexp.setText(_translate("TenshiCore", "Explicações"))
        self.menuOp_es.setTitle(_translate("TenshiCore", "Opções"))
        self.menuResetar_valores.setTitle(_translate("TenshiCore", "Resetar..."))
        self.ajuda.setText(_translate("TenshiCore", "Como utilizar"))
        self.salvar.setText(_translate("TenshiCore", "Salvar estrutura"))
        self.carregar.setText(_translate("TenshiCore", "Carregar estrutura"))
        self.resetforces.setText(_translate("TenshiCore", "Esforços"))
        self.resetforces.setShortcut(_translate("TenshiCore", "Ctrl+R"))
        self.resetudo.setText(_translate("TenshiCore", "Tudo"))
        self.resetudo.setShortcut(_translate("TenshiCore", "Ctrl+F"))

    def vigas(self):
        try:
            self.ss.add_element(location=[[self.vigacx1.text(), self.vigacy1.text()],
                                          [self.vigacx2.text(), self.vigacy2.text()]])
            self.vigacx1.setText(self.vigacx2.text())
            self.vigacy1.setText(self.vigacy2.text())
            self.vigacx2.clear()
            self.vigacy2.clear()
            self.updatefig()
        except:
            self.warning()

    def truss(self):
        try:
            if self.trussea.text() == '':
                self.trussea.setText('0')
            self.ss.add_truss_element(location=[[self.trusscx1.text(), self.trusscy1.text()],
                                                [self.trusscx2.text(), self.trusscy2.text()]])
            self.trusscx1.setText(self.trusscx2.text())
            self.trusscy1.setText(self.trusscy2.text())
            self.trusscx2.clear()
            self.trusscy2.clear()
            self.trussea.clear()
            self.updatefig()
        except:
            self.trussea.clear()
            self.warning()

    def node(self):
        try:
            self.ss.insert_node(element_id=int(self.nodpv.text()), location=[self.noduv.text(), self.nodpos.text()])
            self.nodpos.clear()
            self.noduv.clear()
            self.nodpv.clear()
            self.updatefig()
        except:
            self.warning()

    def supfixo(self):
        try:
            self.ss.add_support_hinged(node_id=int(self.fixopos.text()))
            self.fixopos.clear()
            self.updatefig()
            self.showbuttons()
        except:
            self.warning()

    def supmovel(self):
        try:
            if self.moveldir.text() == '':
                self.moveldir.setText('y')
            if self.movelang.text() == '':
                self.movelang.setText('0')
            self.ss.add_support_roll(node_id=int(self.movelpos.text()), direction=str(self.moveldir.text()),
                                     angle=float(self.movelang.text()))
            self.movelpos.clear()
            self.moveldir.clear()
            self.movelang.clear()
            self.updatefig()
            self.showbuttons()
        except:
            self.movelpos.clear()
            self.moveldir.clear()
            self.movelang.clear()
            self.warning()

    def supeng(self):
        try:
            self.ss.add_support_fixed(node_id=int(self.engpos.text()))
            self.updatefig()
            self.showbuttons()
        except:
            self.warning()

    def supspring(self):
        try:
            if self.molares.text() == '':
                self.molares.setText('0')

            if self.molatra.text() == 'x' or 'X':
                self.molatra.setText('1')
            elif self.molatra.text() == 'z' or 'Z':
                self.molatra.setText('2')
            elif self.molatra.text() == 'y' or 'Y':
                self.molatra.setText('3')
            else:
                self.molatra.setText('1')

            self.ss.add_support_spring(node_id=int(self.molapos.text()), translation=int(self.molatra.text()),
                                       k=float(self.molares.text()))#, roll=self.molactrl.text())

            self.molapos.clear()
            self.molatra.clear()
            self.molares.clear()
            self.updatefig()
        except:
            self.molapos.clear()
            self.molatra.clear()
            self.molares.clear()
            self.warning()

    def pointload(self):
        try:
            if self.pontyint.text() == '':
                self.pontyint.setText('0')
            if self.pontxint.text() == '':
                self.pontxint.setText('0')
            if self.pontrot.text() == '':
                self.pontrot.setText('0')
            self.ss.point_load(node_id=int(self.pontpos.text()), Fy=float(self.pontyint.text()),
                               Fx=float(self.pontxint.text()), rotation=float(self.pontrot.text()))
            self.pontpos.clear()
            self.pontyint.clear()
            self.pontxint.clear()
            self.pontrot.clear()
            self.updatefig()
            self.showbuttons()
        except:
            self.pontpos.clear()
            self.pontyint.clear()
            self.pontxint.clear()
            self.pontrot.clear()
            self.warning()

    def load(self):
        try:
            if self.loadq.text() == '':
                self.loadq.setText(self.loadqi.text())
            if self.loadqi.text() == '':
                self.loadqi.setText(self.loadq.text())
            self.ss.q_load(element_id=int(self.distpos.text()), q=float(self.loadq.text()), qi=float(self.loadqi.text()))
            self.distpos.clear()
            self.loadqi.clear()
            self.loadq.clear()
            self.updatefig()
            self.showbuttons()
        except:
            self.warning()

    def moment(self):
        try:
            self.ss.moment_load(node_id=int(self.mompos.text()), Ty=float(self.momint.text()))
            self.momint.clear()
            self.mompos.clear()
            self.updatefig()
            self.showbuttons()
        except:
            self.warning()

    def solve(self):
        try:
            self.ss.solve()
        except:
            # TODO
            element_map = self.ss.element_map.copy()
            supports_hinged = self.ss.supports_hinged.copy()
            supports_roll = self.ss.supports_roll.copy()
            loads_q = self.ss.loads_q.copy()
            print(self.ss.node_map)
            with open(f'Saved\\blank.pkl', 'rb') as f:
                self.ss = pickle.load(f)
            for c in range(len(element_map)):
                self.ss.add_element(location=[[element_map[c][0], element_map[c][1]],
                                              [element_map[c][2], element_map[c][3]]])
            # supports_hinged
            # supports_roll
            # loads_q
            # self.ss.solve()

    def visualize(self):
        try:
            if self.radiostr.isChecked():
                self.figura = self.ss.show_structure(show=False)
            else:
                functions.eq.clear()
                self.solve()
                if self.radionorm.isChecked():
                    self.figura = self.ss.show_axial_force(show=False)
                elif self.radioapo.isChecked():
                    self.figura = self.ss.show_reaction_force(show=False)
                elif self.radiocort.isChecked():
                    self.figura = self.ss.show_shear_force(show=False)
                elif self.radiomom.isChecked():
                    self.figura = self.ss.show_bending_moment(show=False)
                elif self.radiodes.isChecked():
                    self.figura = self.ss.show_displacement(show=False)
                elif self.radioaio.isChecked():
                    self.figura = self.ss.show_results(show=False)
            self.MplWidget.plot(self.figura)
            self.figurefix()
        except:
            pass

    def showexp(self, fname, width, *args, **kwargs):
        # TODO
        geometry_options = {"right": "2cm", "left": "2cm"}
        doc = Document(fname, geometry_options=geometry_options)

        doc.append('Introduction.')

        with doc.create(Section('Olá marilene')):
            doc.append('Olha o que vai te reprovar:')

            with doc.create(Figure(position='htbp')) as plot:
                plot.add_plot(width=NoEscape(width), *args, **kwargs)
                plot.add_caption('Estrutura')

            doc.append('Deu certo')

        doc.append('Ufa.')

        doc.generate_pdf(clean_tex=False)
        # if self.checkexp.isChecked():
        #     plt.show()

    def reset(self):
        self.ss.remove_loads()
        self.updatefig()
        self.esfcont = 0
        self.sethidden()

    def resetall(self):
        with open(f'Saved\\blank.pkl', 'rb') as f:
            self.ss = pickle.load(f)
        self.carregart.clear()
        self.radiostr.setChecked(True)
        self.MplWidget.plot()
        self.figurefix()
        self.sethidden()
        self.tabWidget.setCurrentIndex(0)

    def save(self):
        with open(f'Saved\\{self.salvart.text()}.pkl', 'wb') as f:
            pickle.dump(self.ss, f)
        self.salvart.clear()

    def sload(self):
        try:
            with open(f'Saved\\{self.carregart.text()}.pkl', 'rb') as f:
                self.ss = pickle.load(f)
            self.carregart.clear()
            self.updatefig()
            self.showbuttons()
        except:
            msg = QMessageBox()
            msg.setWindowTitle("Erro")
            msg.setText("Essa estrutura não existe")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()

    def warning(self):
        msg = QMessageBox()
        msg.setWindowTitle("Erro")
        msg.setText("É necessário mais informações para adicionar")
        msg.setIcon(QMessageBox.Warning)
        x = msg.exec_()

    def updatefig(self):
        if self.radiostr.isChecked():
            pass
        else:
            self.radiostr.setChecked(True)
        self.visualize()
        self.figurefix()

    def figurefix(self):
        x = self.MplWidget.size().width()
        y = self.MplWidget.size().height()
        self.MplWidget.resize(x + 1, y + 1)
        self.MplWidget.resize(x, y)

    def showbuttons(self):
        if (len(self.ss.supports_roll) + len(self.ss.supports_hinged) + len(self.ss.supports_spring_x) +
            len(self.ss.supports_spring_z) + len(self.ss.supports_spring_y) >= 2 or len(self.ss.supports_fixed) >= 1) \
                and (len(self.ss.loads_point) or len(self.ss.loads_q) or len(self.ss.loads_moment)) >= 1:
            self.radioaio.setHidden(False)
            self.radiomom.setHidden(False)
            self.radiocort.setHidden(False)
            self.radioapo.setHidden(False)
            self.radiodes.setHidden(False)
            self.radionorm.setHidden(False)
            self.checkexp.setHidden(False)

    def sethidden(self):
        self.radioaio.setHidden(True)
        self.radiomom.setHidden(True)
        self.radiocort.setHidden(True)
        self.radioapo.setHidden(True)
        self.radiodes.setHidden(True)
        self.radionorm.setHidden(True)
        self.checkexp.setHidden(True)
        self.radiostr.setChecked(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TenshiCore = QtWidgets.QMainWindow()
    ui = Ui_TenshiCore()
    ui.setupUi(TenshiCore)
    TenshiCore.show()
    sys.exit(app.exec_())
